spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useSSL=false
    username: root
    password: 123456
  freemarker:
    charset: UTF-8
    suffix: .ftl
    content-type: text/html
    enabled: true
    cache: false
    template-loader-path: classpath:/templates/
    request-context-attribute: request


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xander.myblog.entity
logging:
  config: classpath:logback-spring.xml

com:
  xander:
    myblog:
      login-interceptor:
        include-patterns:
          - /**
        exclude-patterns:
          - /login
          - /error



server:
  servlet:
    context-path: /myblog
